development:
  domain: localhost:5984
  database: couch_spring_alt
  
test:
  domain: localhost:5984
  database: couch_spring_alt_test
  
  
production:
  protocol: https
  username: kane
  password: password
  domain: rubyghetto.com:5984
  database: couch_spring_alt_the_way    